### ISSUE TITLE
Can't build WASM app due to AssemblyResolutionException

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Wasm.Bootstrap#160]
When I attempt to build a WASM project on latest stable versions of Uno I get:

```
1>C:\...\Uno.Wasm.Bootstrap.targets(125,5): error : Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.Win32.Registry, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
1>C:\...\Uno.Wasm.Bootstrap.targets(125,5): error :    at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
1>C:\...\Uno.Wasm.Bootstrap.targets(125,5): error :    at Driver.Import(String ra, AssemblyKind kind)
1>C:\...\Uno.Wasm.Bootstrap.targets(125,5): error :    at Driver.Import(String ra, AssemblyKind kind)
1>C:\...\Uno.Wasm.Bootstrap.targets(125,5): error :    at Driver.Import(String ra, AssemblyKind kind)
1>C:\...\Uno.Wasm.Bootstrap.targets(125,5): error :    at Driver.Import(String ra, AssemblyKind kind)
1>C:\...\Uno.Wasm.Bootstrap.targets(125,5): error :    at Driver.Import(String ra, AssemblyKind kind)
1>C:\...\Uno.Wasm.Bootstrap.targets(125,5): error :    at Driver.Import(String ra, AssemblyKind kind)
1>C:\...\Uno.Wasm.Bootstrap.targets(125,5): error :    at Driver.Import(String ra, AssemblyKind kind)
1>C:\...\Uno.Wasm.Bootstrap.targets(125,5): error :    at Driver.Run(String[] args)
1>C:\...\Uno.Wasm.Bootstrap.targets(125,5): error :    at Driver.Main(String[] args)
1>C:\...\Uno.Wasm.Bootstrap.targets(125,5): error : System.Exception: Failed to generate wasm layout (More details are available in diagnostics mode or using the MSBuild /bl switch)
1>C:\...\Uno.Wasm.Bootstrap.targets(125,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v1be21f07f93cd3a369c95001065dbda54db9dca8.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 454
1>C:\...\Uno.Wasm.Bootstrap.targets(125,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v1be21f07f93cd3a369c95001065dbda54db9dca8.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 149
```

I tried purging `bin`, `obj` and restarting VS, PC, but nothing helped yet.

VS version - 16.4.2
Wasm.Bootstrap version: 1.0.10 (but not even downgrading helps)

**Comment by MartinZikmund** [comment]
Saw similar problem here - https://github.com/unoplatform/cybertruck/issues/23, but none of the suggestions apply, unfortunately. Project path is short, user name is only single word, no special characters.

**Comment by MartinZikmund** [comment]
Got it. Something, somehow, went wrong when `mono-wasm` was downloaded. I had to into:

    C:\Users\{User}\AppData\Local\Temp\

Deleted the `mono-wasm-??????` folder and done a full rebuild. This re-downloads `mono-wasm` and it works again.
