### ISSUE TITLE
Mono.Linker.Steps.XmlResolutionException after adding assembly to LinkerConfig.xml

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/Uno.Wasm.Bootstrap#179]
I am hitting a `Mono.Linker.Steps.XmlResolutionException` after I add the preview `MvvmCross.Uno` assembly to the `LinkerConfig.xml` file. Error output is as follows:

> error : Fatal error in Mono IL Linker
> error :
> error : Unhandled Exception: Mono.Linker.Steps.XmlResolutionException: Failed to process XML description: resource App30.Wasm.xml in App30.Wasm, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null ---> System.ArgumentException: Name can not be empty
> error :    at Mono.Cecil.AssemblyNameReference.Parse(String fullName)
> error :    at Mono.Linker.Steps.ResolveFromXmlStep.ProcessAssemblies(LinkContext context, XPathNodeIterator iterator)
> error :    at Mono.Linker.Steps.ResolveFromXmlStep.Process()
> error :    --- End of inner exception stack trace ---
> error :    at Mono.Linker.Steps.ResolveFromXmlStep.Process()
> error :    at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
> error :    at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
> error :    at Mono.Linker.Pipeline.Process(LinkContext context)
> error :    at Mono.Linker.Driver.Run(ILogger customLogger)
> error :    at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
> error :    at Mono.Linker.Driver.Main(String[] args)
> error : System.Exception: Failed to execute the linker
> error :    at Uno.Wasm.Bootstrap.ShellTask_v41a20d03691000ce4bf68bdbe75bcd599e866b42.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 626
> error :    at Uno.Wasm.Bootstrap.ShellTask_v41a20d03691000ce4bf68bdbe75bcd599e866b42.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 160
> 
> 

**Steps to reproduce**
1. Get [MvvmCross.Uno preview Nuget package ](https://blogimages.builttoroam.com/2019-08-uno-with-mvvmcross/MvvmCross.Uno.6.3.0.nupkg)
2. Create new Uno Platform App
3. Add reference to the MvvmCross NuGet package in the WASM project
4. Add MvvmCross to the `LinkerConfig.xml` file:
```
<linker>
  <assembly fullName="MvvmCross.Uno" />
  <assembly fullname="App30.Wasm" />
  <assembly fullname="Uno.UI" />

  <assembly fullname="System.Core">
	<!-- This is required by JSon.NET and any expression.Compile caller -->
	<type fullname="System.Linq.Expressions*" />
  </assembly>
</linker>
```
5. Try to build the WASM head. Notice the build fails and error is output.

**Comment by jeromelaban** [comment]
This looks like the MvvmCross.Uno package also has a linker definition file that is not correctly formatted.

**Comment by rizaanlakay** [comment]
Hi there, is there any way around this issue? I see there hasnt been much traction with MvvmCross on UNO since Mar 2020.

**Comment by jeromelaban** [comment]
This may have changed with .NET 5 support, otherwise changes are needed in mvvm cross.
