### ISSUE TITLE
Error coexisting Uno.Wasm.Bootstrap & WebAssembly.Bindings NuGets

### ISSUE THREAD

**Issue by MarcosCobena** [unoplatform/Uno.Wasm.Bootstrap#193]
1. Create a new empty project with latest Uno.Wasm.Bootstrap preview
2. Add a reference to WebAssembly.Bindings (0.2.2, you'll need to have it locally, but you already know this :-P)
3. Build!

I expect a successful build; however, I get the following error:
```
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error : 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error : Unhandled Exception:
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error : System.IO.IOException: Could not create file "/mnt/c/Users/Marcos/Repositorios/WaveEngine/src/VisualTests/LowLevel/Runners/Wasm/bin/Debug/netstandard2.0/dist/managed/WebAssembly.Bindings.dll". File already exists.
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <a1ae6166591d4020b810288d19af38d4>:0 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) [0x00000] in <a1ae6166591d4020b810288d19af38d4>:0 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions)
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at System.IO.FileSystem.CopyFile (System.String sourceFullPath, System.String destFullPath, System.Boolean overwrite) [0x00035] in <a1ae6166591d4020b810288d19af38d4>:0 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x00062] in <a1ae6166591d4020b810288d19af38d4>:0 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at System.IO.File.Copy (System.String sourceFileName, System.String destFileName) [0x00000] in <a1ae6166591d4020b810288d19af38d4>:0 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at Driver.CopyFile (System.String sourceFileName, System.String destFileName, Driver+CopyType copyType, System.String typeFile) [0x000a1] in <e863e5fa48954a8389ce6485f2a15bb6>:0 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at Driver.Run (System.String[] args) [0x00f33] in <e863e5fa48954a8389ce6485f2a15bb6>:0 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at Driver.Main (System.String[] args) [0x00005] in <e863e5fa48954a8389ce6485f2a15bb6>:0 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error : [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.IOException: Could not create file "/mnt/c/Users/Marcos/Repositorios/WaveEngine/src/VisualTests/LowLevel/Runners/Wasm/bin/Debug/netstandard2.0/dist/managed/WebAssembly.Bindings.dll". File already exists.
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <a1ae6166591d4020b810288d19af38d4>:0 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) [0x00000] in <a1ae6166591d4020b810288d19af38d4>:0 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions)
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at System.IO.FileSystem.CopyFile (System.String sourceFullPath, System.String destFullPath, System.Boolean overwrite) [0x00035] in <a1ae6166591d4020b810288d19af38d4>:0 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x00062] in <a1ae6166591d4020b810288d19af38d4>:0 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at System.IO.File.Copy (System.String sourceFileName, System.String destFileName) [0x00000] in <a1ae6166591d4020b810288d19af38d4>:0 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at Driver.CopyFile (System.String sourceFileName, System.String destFileName, Driver+CopyType copyType, System.String typeFile) [0x000a1] in <e863e5fa48954a8389ce6485f2a15bb6>:0 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at Driver.Run (System.String[] args) [0x00f33] in <e863e5fa48954a8389ce6485f2a15bb6>:0 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :   at Driver.Main (System.String[] args) [0x00005] in <e863e5fa48954a8389ce6485f2a15bb6>:0 
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error : System.Exception: Failed to generate wasm layout (More details are available in diagnostics mode or using the MSBuild /bl switch)
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v1e4fc8b053d7599d2bba00cf39b106f39c6d9ee7.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 524
18>C:\Users\Marcos\.nuget\packages\uno.wasm.bootstrap\1.2.0-dev.24\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v1e4fc8b053d7599d2bba00cf39b106f39c6d9ee7.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 165
```

Thanks in advance,

—Marcos

**Comment by jeromelaban** [comment]
Interesting case. Indeed this may happen as we're not using any of the bindings in Uno apps at this point (it's a bit too expensive perf wisse, compared to InvokeJSUnmarshaled and Marhal.StructToPtr), but it should be easy to workaround.

I can think of adding a change that detects the presence of that package, and does not use the ones from the SDK, or the other way around.
