### ISSUE TITLE
Failed to create a directory when publishing

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/Uno.Wasm.Bootstrap#279]
When publishing to Azure:
.nuget\packages\uno.wasm.bootstrap\1.4.0-dev.45\build\Uno.Wasm.Bootstrap.targets(128,2): Error : Failed to create directory \bin\Debug\netstandard2.1\dist]
Because of this, publishing always fails.

**Comment by jeromelaban** [comment]
This issue can be fixed by adding the following to the project:

```xml
<PropertyGroup>
  <WasmShellEnableLongPathSupport>false</WasmShellEnableLongPathSupport>
</PropertyGroup>
```

This looks like it's machine dependent as it's not present all the time.

**Comment by HavenDV** [comment]
Thanks. This fixed the problem. But after publishing the application still gives the error "Error: 404 Not Found"

**Comment by jeromelaban** [comment]
This could happen if the original build failed. Do you see an index.html file in the deployment folder ?

**Comment by HavenDV** [comment]
In addition, when publishing when building a clean project (after deleting the bin and obj directories), the first attempt always fails:

```
CSC(0,0): Error CS2012: Cannot open '\obj\Release\netstandard2.1\Dedoose.Wasm.dll' for writing -- 'The process cannot access the file '\obj\Release\netstandard2.1\Dedoose.Wasm.dll' because it is being used by another process.'
```

**Comment by jeromelaban** [comment]
Thanks I see that you've updated your project to netstandard2.1, this is not yet supported. Can you try with netstandard2.0 ?

**Comment by HavenDV** [comment]
Simply switching to netstandard2.0 didn't help. I am trying to re-create services.

**Comment by jeromelaban** [comment]
Thanks. Does the project build and run without publishing ?

**Comment by HavenDV** [comment]
Yes, but only for a debug configuration.

**Comment by jeromelaban** [comment]
What happens in release? Could you provide the msbuild.binlog file created when running `msbuild /r /bl /p:Configuration=Release` in your Wasm project folder ?

**Comment by HavenDV** [comment]
Log:
[log.txt](https://github.com/unoplatform/Uno.Wasm.Bootstrap/files/5279931/log.txt)

**Comment by HavenDV** [comment]
After adding files to LinkerConfig.xml, I see a new issue:
```xml
<linker>
  <assembly fullname="CommonServiceLocator" />
  <assembly fullname="Dedoose.API.Client" />
  <assembly fullname="Dedoose.Core" />
  <assembly fullname="Dedoose.Wasm" />
  <assembly fullname="DynamicData" />
  <assembly fullname="Microsoft.Bcl.AsyncInterfaces" />
  <assembly fullname="Microsoft.Extensions.Configuration.Abstractions" />
  <assembly fullname="Microsoft.Extensions.Configuration.Binder" />
  <assembly fullname="Microsoft.Extensions.Configuration.CommandLine" />
  <assembly fullname="Microsoft.Extensions.Configuration" />
  <assembly fullname="Microsoft.Extensions.Configuration.EnvironmentVariables" />
  <assembly fullname="Microsoft.Extensions.Configuration.FileExtensions" />
  <assembly fullname="Microsoft.Extensions.Configuration.Json" />
  <assembly fullname="Microsoft.Extensions.Configuration.UserSecrets" />
  <assembly fullname="Microsoft.Extensions.DependencyInjection.Abstractions" />
  <assembly fullname="Microsoft.Extensions.DependencyInjection" />
  <assembly fullname="Microsoft.Extensions.FileProviders.Abstractions" />
  <assembly fullname="Microsoft.Extensions.FileProviders.Physical" />
  <assembly fullname="Microsoft.Extensions.FileSystemGlobbing" />
  <assembly fullname="Microsoft.Extensions.Hosting.Abstractions" />
  <assembly fullname="Microsoft.Extensions.Hosting" />
  <assembly fullname="Microsoft.Extensions.Logging.Abstractions" />
  <assembly fullname="Microsoft.Extensions.Logging.Configuration" />
  <assembly fullname="Microsoft.Extensions.Logging.Console" />
  <assembly fullname="Microsoft.Extensions.Logging.Debug" />
  <assembly fullname="Microsoft.Extensions.Logging" />
  <assembly fullname="Microsoft.Extensions.Logging.EventLog" />
  <assembly fullname="Microsoft.Extensions.Logging.EventSource" />
  <assembly fullname="Microsoft.Extensions.Options.ConfigurationExtensions" />
  <assembly fullname="Microsoft.Extensions.Options" />
  <assembly fullname="Microsoft.Extensions.Primitives" />
  <assembly fullname="Newtonsoft.Json" />
  <assembly fullname="ReactiveUI" />
  <assembly fullname="ReactiveUI.Fody.Helpers" />
  <assembly fullname="ReactiveUI.Uno" />
  <assembly fullname="Splat" />
  <assembly fullname="Splat.Microsoft.Extensions.DependencyInjection" />
  <assembly fullname="System.Buffers" />
  <assembly fullname="System.Collections.Immutable" />
  <assembly fullname="System.ComponentModel.Annotations" />
  <assembly fullname="System.ComponentModel" />
  <assembly fullname="System.Diagnostics.Contracts" />
  <assembly fullname="System.Diagnostics.EventLog" />
  <assembly fullname="System.Dynamic.Runtime" />
  <assembly fullname="System.Linq" />
  <assembly fullname="System.Linq.Expressions" />
  <assembly fullname="System.Memory" />
  <assembly fullname="System.Numerics.Vectors" />
  <assembly fullname="System.ObjectModel" />
  <assembly fullname="System.Reactive" />
  <assembly fullname="System.Reactive.Wasm" />
  <assembly fullname="System.Reflection.Emit" />
  <assembly fullname="System.Reflection.Emit.ILGeneration" />
  <assembly fullname="System.Reflection.Emit.Lightweight" />
  <assembly fullname="System.Runtime.CompilerServices.Unsafe" />
  <assembly fullname="System.Runtime.InteropServices.WindowsRuntime" />
  <assembly fullname="System.Runtime.Serialization.Primitives" />
  <assembly fullname="System.Security.Principal.Windows" />
  <assembly fullname="System.Text.Encodings.Web" />
  <assembly fullname="System.Text.Json" />
  <assembly fullname="System.Threading" />
  <assembly fullname="System.Threading.Tasks.Extensions" />
  <assembly fullname="Uno.Core" />
  <assembly fullname="Uno.Diagnostics.Eventing" />
  <assembly fullname="Uno" />
  <assembly fullname="Uno.Foundation" />
  <assembly fullname="Uno.Foundation.Runtime.WebAssembly" />
  <assembly fullname="Uno.UI" />
  <assembly fullname="Uno.UI.FluentTheme" />
  <assembly fullname="Uno.UI.Runtime.WebAssembly" />
  <assembly fullname="Uno.UI.Toolkit" />
  <assembly fullname="Uno.Xaml" />
</linker>
```

```
Error: System.PlatformNotSupportedException: Cannot start threads on this runtime.
  at (wrapper managed-to-native) System.Threading.Thread.Thread_internal(System.Threading.Thread,System.MulticastDelegate)
  at System.Threading.Thread.StartInternal (System.Object principal, System.Threading.StackCrawlMark& stackMark) <0x3745418 + 0x00010> in <filename unknown>:0 
  at System.Threading.Thread.Start (System.Threading.StackCrawlMark& stackMark) <0x3745318 + 0x0005a> in <filename unknown>:0 
  at System.Threading.Thread.Start () <0x3745260 + 0x0001a> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.Console.ConsoleLoggerProcessor..ctor () <0x3738430 + 0x00060> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider..ctor (Microsoft.Extensions.Options.IOptionsMonitor`1[TOptions] options) <0x36ff150 + 0x0006c> in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) <0x318d618 + 0x0002a> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---

  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context) <0x36cebe0 + 0x00100> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSiteMain (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, TArgument argument) <0x364efa8 + 0x000a6> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope serviceProviderEngine, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverLock lockType) <0x36b3e18 + 0x000c0> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context) <0x36adf48 + 0x00030> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, TArgument argument) <0x364ea70 + 0x000a0> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable (Microsoft.Extensions.DependencyInjection.ServiceLookup.IEnumerableCallSite enumerableCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context) <0x364f350 + 0x0005e> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSiteMain (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, TArgument argument) <0x364efa8 + 0x00084> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope serviceProviderEngine, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverLock lockType) <0x36b3e18 + 0x000c0> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context) <0x36adf48 + 0x00030> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, TArgument argument) <0x364ea70 + 0x000a0> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context) <0x36cebe0 + 0x00078> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSiteMain (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, TArgument argument) <0x364efa8 + 0x000a6> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope serviceProviderEngine, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverLock lockType) <0x36b3e18 + 0x000c0> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context) <0x36adf48 + 0x00030> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, TArgument argument) <0x364ea70 + 0x000a0> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context) <0x36cebe0 + 0x00078> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSiteMain (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, TArgument argument) <0x364efa8 + 0x000a6> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope serviceProviderEngine, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverLock lockType) <0x36b3e18 + 0x000c0> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context) <0x36adf48 + 0x00030> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, TArgument argument) <0x364ea70 + 0x000a0> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context) <0x36cebe0 + 0x00078> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSiteMain (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, TArgument argument) <0x364efa8 + 0x000a6> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope serviceProviderEngine, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverLock lockType) <0x36b3e18 + 0x000c0> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context) <0x36adf48 + 0x00030> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, TArgument argument) <0x364ea70 + 0x000a0> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context) <0x36cebe0 + 0x00078> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSiteMain (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, TArgument argument) <0x364efa8 + 0x000a6> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope serviceProviderEngine, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverLock lockType) <0x36b3e18 + 0x000c0> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext context) <0x36adf48 + 0x00030> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, TArgument argument) <0x364ea70 + 0x000a0> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) <0x364e538 + 0x00036> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine+<>c__DisplayClass1_0.<RealizeService>b__0 (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) <0x364e3e0 + 0x00072> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService (System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope serviceProviderEngineScope) <0x363bbf8 + 0x00076> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService (System.Type serviceType) <0x3637790 + 0x00014> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService (System.Type serviceType) <0x3637660 + 0x00014> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService (System.IServiceProvider provider, System.Type serviceType) <0x3637508 + 0x0006e> in <filename unknown>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T] (System.IServiceProvider provider) <0x36b53d8 + 0x00024> in <filename unknown>:0 
  at Microsoft.Extensions.Hosting.HostBuilder.Build () <0x3317240 + 0x00068> in <filename unknown>:0 
  at Dedoose.InitializeMethods.Initialize () <0x32f7f58 + 0x00092> in <filename unknown>:0 
  at Dedoose.App..ctor () <0x32bcf40 + 0x00046> in <filename unknown>:0 
  at Dedoose.Wasm.Program+<>c.<Main>b__4_0 (Windows.UI.Xaml.ApplicationInitializationCallbackParams _) <0x32b8868 + 0x00006> in <filename unknown>:0 
  at Windows.UI.Xaml.Application.StartPartial (Windows.UI.Xaml.ApplicationInitializationCallback callback) <0x322fcd8 + 0x00072> in <filename unknown>:0 
  at Windows.UI.Xaml.Application.Start (Windows.UI.Xaml.ApplicationInitializationCallback callback) <0x322f6f8 + 0x0000a> in <filename unknown>:0 
  at Dedoose.Wasm.Program.Main () <0x321bd18 + 0x0002e> in <filename unknown>:0 
    at Object.call_method (http://localhost:56599/package_d1b425453708281c8e1fdc778e067da211ed2cf7/dotnet.js:1:170392)
    at Object.mainInit (http://localhost:56599/package_d1b425453708281c8e1fdc778e067da211ed2cf7/uno-bootstrap.js:181:25)
    at checkDone (http://localhost:56599/package_d1b425453708281c8e1fdc778e067da211ed2cf7/uno-bootstrap.js:433:25)
    at processDependency (http://localhost:56599/package_d1b425453708281c8e1fdc778e067da211ed2cf7/uno-bootstrap.js:457:25)
    at Object.execCb (http://localhost:56599/package_d1b425453708281c8e1fdc778e067da211ed2cf7/require.js:5:16727)
    at e.check (http://localhost:56599/package_d1b425453708281c8e1fdc778e067da211ed2cf7/require.js:5:10499)
    at e.<anonymous> (http://localhost:56599/package_d1b425453708281c8e1fdc778e067da211ed2cf7/require.js:5:12915)
    at http://localhost:56599/package_d1b425453708281c8e1fdc778e067da211ed2cf7/require.js:5:1542
    at http://localhost:56599/package_d1b425453708281c8e1fdc778e067da211ed2cf7/require.js:5:13376
    at each (http://localhost:56599/package_d1b425453708281c8e1fdc778e067da211ed2cf7/require.js:5:1020)
```

**Comment by jeromelaban** [comment]
Thank you. Make sure to keep the logging packages to the version 1.1.1, as later builds use threads that are not available yet for WebAssembly.

**Comment by HavenDV** [comment]
Release build starts successfully after I downgraded the Nuget version of packages to:
```xml
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Filter" Version="1.1.2" />
```

But publishing to Azure still throws an error:
![image](https://user-images.githubusercontent.com/3002068/94221182-e6dbd800-ff2d-11ea-816d-88e18c027c48.png)

**Comment by jeromelaban** [comment]
This is good news. This last error generally means that the web.config file is not present, which could be a 1.4-dev issue. Could you try downgrading to the last stable build of the bootstrapper (1.3.4) ?

**Comment by HavenDV** [comment]
1.3.4 - similar problem
1.3.0 - similar problem
1.2.0 - Release - Linker Error:
```
1>------ Build started: Project: Dedoose.Wasm, Configuration: Release Any CPU ------
1>Dedoose.Wasm -> C:\Users\haven\source\repos\JTtheGeek\DedooseNextGenClient\src\App\Dedoose.Wasm\bin\Release\netstandard2.0\Dedoose.Wasm.dll
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error : Fatal error in Mono IL Linker
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error : Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve Windows.UI.Xaml.UIElement/EventArgsParser
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field)
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.MarkFields(TypeDefinition type, Boolean includeStatic, Boolean markBackingFieldsOnlyIfPropertyMarked)
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.ApplyPreserveInfo(TypeDefinition type)
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.Initialize()
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Pipeline.Process(LinkContext context)
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Driver.Run(ILogger customLogger)
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Mono.Linker.Driver.Main(String[] args)
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error : System.Exception: Failed to execute the linker
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 664
1>C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.2.0\build\Uno.Wasm.Bootstrap.targets(124,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v44d638e0a943d17f8df83f1432fdc85b8ed83fd4.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 168
1>Done building project "Dedoose.Wasm.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========
```
1.2.0 Debug:
![image](https://user-images.githubusercontent.com/3002068/94335120-ab6c0700-001c-11eb-960b-07677ea55ba7.png)

**Comment by jeromelaban** [comment]
I've found the issue with the locked file you mentioned previously, but the last error (failed to execute compile) is very curious. We have yet to document this but are you deploying to a .NET Framework web app ? Deploying to another app type (.NET Core may be one) could fail because the `.wasm` extension does not have the proper mime type.

In the network tab, does the `dotnet.wasm` download succeed ?

**Comment by HavenDV** [comment]
Yes, the default is .Net Core when publishing. I tried changing to .Net 4.7 but the problem persists. TargetFramework when published is .net standard 2.0

> In the network tab, does the dotnet.wasm download succeed ?
![image](https://user-images.githubusercontent.com/3002068/94393995-a2f00980-019f-11eb-8e56-02383bcf78c4.png)

**Comment by jeromelaban** [comment]
Thanks. This most likely means that the deployment target is not the right one. You need to create a .NET 4.7 azure app service: 

Here's a configuration example:
![image](https://user-images.githubusercontent.com/5839577/94430679-4c180f00-0162-11eb-94d6-45b26828c496.png)

**Comment by HavenDV** [comment]
Similar problem after changing settings and restarting the server. I also tried to publish the application, it had no effect.

**Comment by jeromelaban** [comment]
Can you validate that the dotnet.wasm file and web.config files are deployed to your azure web app ?

**Comment by HavenDV** [comment]
dotnet.wasm - exists
web.config - missing

**Comment by HavenDV** [comment]
The problem changed after adding a web.config file to the project with the following content:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <staticContent>
      <remove fileExtension=".wasm" />
      <mimeMap fileExtension=".wasm" mimeType="application/wasm" />
    </staticContent>
  </system.webServer>
</configuration>
```

![image](https://user-images.githubusercontent.com/3002068/94505202-e1440200-024d-11eb-9f84-70a1376db8f8.png)

**Comment by jeromelaban** [comment]
Thanks, it looks like there's a web.config publishing issue then. We'll look into this.
