### ISSUE TITLE
2.0.0-dev.180 Breaks EF Core

### ISSUE THREAD

**Issue by groogiam** [unoplatform/Uno.Wasm.Bootstrap#352]
The latest dev version appears to break EF Core Queryable in .NET 5.

The attached repro gives the following error:
[SqlInMemoryWasm.zip](https://github.com/unoplatform/Uno.Wasm.Bootstrap/files/6106509/SqlInMemoryWasm.zip)

```
uno-bootstrap.js:201 Error: System.TypeInitializationException: The type initializer for 'Microsoft.EntityFrameworkCore.Query.QueryableMethods' threw an exception.
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.Single[MethodInfo](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethods..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryableMethodNormalizingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.NormalizeQueryableMethod(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryTranslationPreprocessor.Process(Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[Blog](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[Blog](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[Blog](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1[[SqlInMemoryWasm.Program.Blog, SqlInMemoryWasm, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[Blog](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[Blog](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[Blog](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[Blog](IQueryable`1 source)
   at SqlInMemoryWasm.Program.LoadData(String json)
   at SqlInMemoryWasm.Program.Main(String[] args)
```

**Comment by jeromelaban** [comment]
Thanks for the report. 

This is likely to be a linker error. Can you validate if this works properly by disabling it?

**Comment by groogiam** [comment]
Repro has the linker disabled via <WasmShellILLinkerEnabled>false</WasmShellILLinkerEnabled>. If I change the package back to 2.0.0-dev.167 the issue goes away.

**Comment by jeromelaban** [comment]
Thanks for the update!

**Comment by jeromelaban** [comment]
This is a .NET Runtime issue, where some update in .NET 6 causes this:

If you add this in your project, you can revert back to previous working version:


```  
<PropertyGroup>
	<NetCoreWasmSDKUri>https://unowasmbootstrap.azureedge.net/runtime/dotnet-runtime-wasm-92b14c2-24993-Release.zip</NetCoreWasmSDKUri>
</PropertyGroup>
```

It may have already been fixed upstream. I'll create a more recent build of the runtime package so we can try this out on more recent bits, but if it still fails we'll need to open an issue in dotnet/runtime.
