### ISSUE TITLE
FullAOT is not working for Windows/.NET 5/Ubuntu20.04.

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/Uno.Wasm.Bootstrap#353]
.csproj
```xml
  <WasmShellMonoRuntimeExecutionMode>FullAOT</WasmShellMonoRuntimeExecutionMode>

  <ItemGroup>
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="1.3.6" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="1.3.6" PrivateAssets="all" />
  </ItemGroup>
```

Build Log:
```
2>  Runtime C:\Users\haven\AppData\Local\Temp\mono-wasm-e351637985e\builds\release\zlib-helper.o -> C:\Users\haven\source\repos\DedooseV2\Dedoose.Apps\src\apps\Dedoose.Apps.Uno.WebAssembly\obj\Debug\net5.0\dist_work\zlib-helper.o
2>  Running []: C:\Windows\sysnative\bash.exe -c "   `wslpath \"C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.3.6\build\scripts\emscripten-setup.sh\"` \"C:\\Users\\haven\\source\\repos\\DedooseV2\\Dedoose.Apps\\src\\apps\\Dedoose.Apps.Uno.WebAssembly\\obj\" 1.39.11"
2>  C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.3.6\build\Uno.Wasm.Bootstrap.targets(126,2): error : The Windows Subsystem for Linux dotnet environment may not be properly setup, and you may need to run the environment setup script. Open an Ubuntu WSL shell and run:
2>  C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.3.6\build\Uno.Wasm.Bootstrap.targets(126,2): error : 
2>  C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.3.6\build\Uno.Wasm.Bootstrap.targets(126,2): error : bash -c `wslpath "C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.3.6\build\scripts\dotnet-setup.sh"`
2>  C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.3.6\build\Uno.Wasm.Bootstrap.targets(126,2): error : 
2>  C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.3.6\build\Uno.Wasm.Bootstrap.targets(126,2): error :
2>  C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.3.6\build\Uno.Wasm.Bootstrap.targets(126,2): error : System.InvalidOperationException: Failed to setup WSL environment.
2>  C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.3.6\build\Uno.Wasm.Bootstrap.targets(126,2): error :    at Uno.Wasm.Bootstrap.ShellTask_v65f15688c01a8b60ccec58f45d8389407f0e0bff.ValidateEmscripten() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 848
2>  C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.3.6\build\Uno.Wasm.Bootstrap.targets(126,2): error :    at Uno.Wasm.Bootstrap.ShellTask_v65f15688c01a8b60ccec58f45d8389407f0e0bff.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 575
2>  C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.3.6\build\Uno.Wasm.Bootstrap.targets(126,2): error :    at Uno.Wasm.Bootstrap.ShellTask_v65f15688c01a8b60ccec58f45d8389407f0e0bff.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 182
2>Done building target "BuildDist" in project "Dedoose.Apps.Uno.WebAssembly.csproj" -- FAILED.
```

The script passes bad arguments. Worked version:
```
sudo bash -c '`wslpath "C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.3.6\build\scripts\emscripten-setup.sh"` "$0" "$1"' `wslpath 'C:\Users\haven\source\repos\DedooseV2\Dedoose.Apps\src\apps\Dedoose.Apps.Uno.WebAssembly\obj\'` 1.39.11
```
Info about passing arguments: https://unix.stackexchange.com/questions/144514/add-arguments-to-bash-c

P.S. `2.0.0-dev.180` also does not work:
```
Running []: C:\Windows\sysnative\bash.exe -c "   `wslpath \"C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\2.0.0-dev.180\build\scripts\emscripten-setup.sh\"` \"$HOME/.uno/emsdk\" 2.0.12"
```
I think the problem is the same with the arguments.

**Comment by HavenDV** [comment]
In addition, the install script tries to install dotnet-sdk-3.0, which is no longer supported and is also not available.

**Comment by HavenDV** [comment]
Similar issue with Uno.Wasm.SampleNet5.Aot:
```
Runtime: C:\Users\haven\AppData\Local\Temp\dotnet-runtime-wasm-8310d58-c11604786a8-26003-Release\runtimes\browser-wasm\native\pinvoke.h -> \\?\C:\Users\haven\Downloads\Uno.Wasm.Bootstrap-main\Uno.Wasm.Bootstrap-main\src\Uno.Wasm.SampleNet5.Aot\obj\Debug\net5\dist_work\pinvoke.h
7>  Running []: C:\Windows\sysnative\bash.exe -c "   `wslpath \"C:\Users\haven\Downloads\Uno.Wasm.Bootstrap-main\Uno.Wasm.Bootstrap-main\src\Uno.Wasm.Bootstrap\build\scripts\emscripten-setup.sh\"` \"$HOME/.uno/emsdk\" 2.0.12"
7>  C:\Users\haven\Downloads\Uno.Wasm.Bootstrap-main\Uno.Wasm.Bootstrap-main\src\Uno.Wasm.Bootstrap\build\Uno.Wasm.Bootstrap.targets(172,2): error : The Windows Subsystem for Linux dotnet environment may not be properly setup, and you may need to run the environment setup script. Open an Ubuntu WSL shell and run:
7>  C:\Users\haven\Downloads\Uno.Wasm.Bootstrap-main\Uno.Wasm.Bootstrap-main\src\Uno.Wasm.Bootstrap\build\Uno.Wasm.Bootstrap.targets(172,2): error : 
7>  C:\Users\haven\Downloads\Uno.Wasm.Bootstrap-main\Uno.Wasm.Bootstrap-main\src\Uno.Wasm.Bootstrap\build\Uno.Wasm.Bootstrap.targets(172,2): error : bash -c `wslpath "C:\Users\haven\Downloads\Uno.Wasm.Bootstrap-main\Uno.Wasm.Bootstrap-main\src\Uno.Wasm.Bootstrap\build\scripts\dotnet-setup.sh"`
7>  C:\Users\haven\Downloads\Uno.Wasm.Bootstrap-main\Uno.Wasm.Bootstrap-main\src\Uno.Wasm.Bootstrap\build\Uno.Wasm.Bootstrap.targets(172,2): error : 
7>  C:\Users\haven\Downloads\Uno.Wasm.Bootstrap-main\Uno.Wasm.Bootstrap-main\src\Uno.Wasm.Bootstrap\build\Uno.Wasm.Bootstrap.targets(172,2): error :
7>  C:\Users\haven\Downloads\Uno.Wasm.Bootstrap-main\Uno.Wasm.Bootstrap-main\src\Uno.Wasm.Bootstrap\build\Uno.Wasm.Bootstrap.targets(172,2): error : System.InvalidOperationException: Failed to setup WSL environment.
7>  C:\Users\haven\Downloads\Uno.Wasm.Bootstrap-main\Uno.Wasm.Bootstrap-main\src\Uno.Wasm.Bootstrap\build\Uno.Wasm.Bootstrap.targets(172,2): error :    at Uno.Wasm.Bootstrap.ShellTask_v0.ValidateEmscripten() in C:\Users\haven\Downloads\Uno.Wasm.Bootstrap-main\Uno.Wasm.Bootstrap-main\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 961
7>  C:\Users\haven\Downloads\Uno.Wasm.Bootstrap-main\Uno.Wasm.Bootstrap-main\src\Uno.Wasm.Bootstrap\build\Uno.Wasm.Bootstrap.targets(172,2): error :    at Uno.Wasm.Bootstrap.ShellTask_v0.RunPackager() in C:\Users\haven\Downloads\Uno.Wasm.Bootstrap-main\Uno.Wasm.Bootstrap-main\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 659
7>  C:\Users\haven\Downloads\Uno.Wasm.Bootstrap-main\Uno.Wasm.Bootstrap-main\src\Uno.Wasm.Bootstrap\build\Uno.Wasm.Bootstrap.targets(172,2): error :    at Uno.Wasm.Bootstrap.ShellTask_v0.Execute() in C:\Users\haven\Downloads\Uno.Wasm.Bootstrap-main\Uno.Wasm.Bootstrap-main\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 214
7>Done building target "BuildDist" in project "Uno.Wasm.SampleNet5.Aot.csproj" -- FAILED.
```

**Comment by jeromelaban** [comment]
You can run the script, but once it's done, you'll need to install .NET 5 manually:

https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004-

We'll adjust the script based on the distribution

**Comment by HavenDV** [comment]
.NET 5 is already installed.

ShellTask.cs
```cs
var result = RunProcess(
    emscriptenSetupScript,
    $"\"{emsdkHostFolder.Replace("\\\\?\\", "").TrimEnd('\\')}\" {CurrentEmscriptenVersion}");

if (result.exitCode == 0)
{
    return emsdkBaseFolder + $"/emsdk";
}

var dotnetSetupScript = Path.Combine(BuildTaskBasePath, "scripts", "dotnet-setup.sh");
AdjustFileLineEndings(dotnetSetupScript);

Log.LogError(
	$"The Windows Subsystem for Linux dotnet environment may not be properly setup, and you may need to run " +
	$"the environment setup script. Open an Ubuntu WSL shell and run:\n\nbash -c `wslpath \"{dotnetSetupScript}\"`\n\n");

throw new InvalidOperationException($"Failed to setup WSL environment.");
```

This code starts the emscripten installation process, but returns -1 because the arguments were passed incorrectly.
This can be understood from the log, because (I have the display of Build messages at the Normal level enabled) the process being launched does not write anything to the log, except for this line:
```
Running []: C:\Windows\sysnative\bash.exe -c "   `wslpath 
\"C:\Users\haven\.nuget\packages\uno.wasm.bootstrap\1.3.6\build\scripts\emscripten-setup.sh\"` \"C:\\Users\\haven\\source\\repos\\DedooseV2\\Dedoose.Apps\\src\\apps\\Dedoose.Apps.Uno.WebAssembly\\obj\" 1.39.11"
```

ShellTask.cs/RunProcess
```cs
Log.LogMessage($"Running [{p.StartInfo.WorkingDirectory}]: {p.StartInfo.FileName} {p.StartInfo.Arguments}");

var output = new StringBuilder();
var error = new StringBuilder();
var elapsed = Stopwatch.StartNew();
p.OutputDataReceived += (s, e) => { if (e.Data != null) { Log.LogMessage($"[{elapsed.Elapsed}] {e.Data}"); output.Append(e.Data); } };
p.ErrorDataReceived += (s, e) => { if (e.Data != null) { Log.LogError($"[{elapsed.Elapsed}] {e.Data}"); error.Append(e.Data); } };
```

**Comment by jeromelaban** [comment]
Thanks for the update.

**Comment by jeromelaban** [comment]
This has been fixed by a combination of boostrapper validations and uno-check.
