### ISSUE TITLE
IntermediateOutputPath to support absolute path.

### ISSUE THREAD

**Issue by veler** [unoplatform/Uno.Wasm.Bootstrap#648]
Hi,

I usually like to tweak my solution by setting the `bin` and `obj` folders to be in the root of the repository. I do it this way:

```
    <!-- Defines the bin and obj folder paths -->
    <RepoRoot>$([System.IO.Path]::GetDirectoryName($([MSBuild]::GetPathOfFileAbove('.gitignore', '$(MSBuildThisFileDirectory)'))))\</RepoRoot>
    <BaseOutputPath>$(RepoRoot)bin\$(Configuration)\$(Platform)\</BaseOutputPath>
    <OutputPath>$(BaseOutputPath)$(MSBuildProjectName)\</OutputPath>
    <BaseIntermediateOutputPath>$(RepoRoot)obj\$(Platform)\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)\$(Configuration)</IntermediateOutputPath>
    <GeneratedFilesDir>$(BaseIntermediateOutputPath)Generated Files\</GeneratedFilesDir>
    <PackagesConfigRestorePath>$(RepoRoot)packages\</PackagesConfigRestorePath>
```

However it doesn't work in a project that use `Uno.Wasm.Bootstrap` because of the following line that includes the project folder by default and assume that `IntermediateOutputPath` would be a relative path to the current project directory:

https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/56f2bad0268ab4e80e07a72e2e42cf6773492b6c/src/Uno.Wasm.Bootstrap/build/Uno.Wasm.Bootstrap.targets#L225

Would it be possible to make `Uno.Wasm.Bootstrap` supporting absolute and relative paths?

**Comment by jeromelaban** [comment]
@veler this should be good to go soon in the 8.0-dev.X packages, as a validation. I'll backport it soon to the 7.0.x branch as well.

**Comment by veler** [comment]
Awesome! Thank you very much! I will try to give it a try sometime this week :)

**Comment by veler** [comment]
Hello @jeromelaban,

I gave it a try and it's almost good :)
Using the `8.0.0-dev.60` package, the project build, however, starting debugging immediately crashes with a similar error:

```
[...]
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.11\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Hosting.Diagnostics: Critical: Application startup exception

System.IO.DirectoryNotFoundException: D:\Repos\DevToys\src\app\dev\platforms\DevToys.Wasm\D:\Repos\DevToys\bin\Debug\AnyCPU\DevToys.Wasm\net6.0\dist\
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Uno.Wasm.Bootstrap.Cli.Server.Startup.Configure(IApplicationBuilder app, IConfiguration configuration) in /_/src/Uno.Wasm.Bootstrap.Cli/Server/Startup.cs:line 75
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
The thread 0x62b8 has exited with code 0 (0x0).
An unhandled exception of type 'System.IO.DirectoryNotFoundException' occurred in System.Private.CoreLib.dll
D:\Repos\DevToys\src\app\dev\platforms\DevToys.Wasm\D:\Repos\DevToys\bin\Debug\AnyCPU\DevToys.Wasm\net6.0\dist\
```

I can workaround the problem by manually setting the Output path relative to the current project directory:
```xml
    <BaseOutputPath>bin\$(Configuration)\$(Platform)\</BaseOutputPath>
    <OutputPath>$(BaseOutputPath)$(MSBuildProjectName)\</OutputPath>
```

I imagine a similar change is needed to fix it?
Would you like me to open a new issue for it or keep iterate on the current one?

**Comment by jeromelaban** [comment]
Thanks for trying it out! A similar change is needed indeed, that a deployment change that may cause a bit more trouble, we'll see :)

Let's reopen until this is fixed.
