### ISSUE TITLE
Wasm build fails

### ISSUE THREAD

**Issue by fatichar** [unoplatform/Uno.Wasm.Bootstrap#656]
I get this error when I build my WASM project:
```
5>C:\Users\pravi\.nuget\packages\uno.wasm.bootstrap\7.0.11\build\Uno.Wasm.Bootstrap.targets(207,3): error : [00:00:00.8103018] Unhandled exception. System.Exception: Could not resolve Microsoft.Extensions.Configuration.FileExtensions
5>C:\Users\pravi\.nuget\packages\uno.wasm.bootstrap\7.0.11\build\Uno.Wasm.Bootstrap.targets(207,3): error : [00:00:00.8103483]    at Driver.Resolve(String asm_name, AssemblyKind& kind) in D:\a\1\s\src\Uno.Wasm.Packager\packager.cs:line 242
5>C:\Users\pravi\.nuget\packages\uno.wasm.bootstrap\7.0.11\build\Uno.Wasm.Bootstrap.targets(207,3): error : [00:00:00.8103571]    at Driver.Import(String ra, AssemblyKind kind) in D:\a\1\s\src\Uno.Wasm.Packager\packager.cs:line 310
5>C:\Users\pravi\.nuget\packages\uno.wasm.bootstrap\7.0.11\build\Uno.Wasm.Bootstrap.targets(207,3): error : [00:00:00.8103587]    at Driver.Import(String ra, AssemblyKind kind) in D:\a\1\s\src\Uno.Wasm.Packager\packager.cs:line 310
5>C:\Users\pravi\.nuget\packages\uno.wasm.bootstrap\7.0.11\build\Uno.Wasm.Bootstrap.targets(207,3): error : [00:00:00.8103594]    at Driver.Run(String[] args) in D:\a\1\s\src\Uno.Wasm.Packager\packager.cs:line 726
5>C:\Users\pravi\.nuget\packages\uno.wasm.bootstrap\7.0.11\build\Uno.Wasm.Bootstrap.targets(207,3): error : [00:00:00.8103835]    at Driver.Main(String[] args) in D:\a\1\s\src\Uno.Wasm.Packager\packager.cs:line 370
5>C:\Users\pravi\.nuget\packages\uno.wasm.bootstrap\7.0.11\build\Uno.Wasm.Bootstrap.targets(207,3): error : System.Exception: Failed to generate wasm layout (More details are available in diagnostics mode or using the MSBuild /bl switch)
5>C:\Users\pravi\.nuget\packages\uno.wasm.bootstrap\7.0.11\build\Uno.Wasm.Bootstrap.targets(207,3): error :    at Uno.Wasm.Bootstrap.ShellTask_v667976303edda96613ed27b40cdf1ccde7b38a60.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 723
5>C:\Users\pravi\.nuget\packages\uno.wasm.bootstrap\7.0.11\build\Uno.Wasm.Bootstrap.targets(207,3): error :    at Uno.Wasm.Bootstrap.ShellTask_v667976303edda96613ed27b40cdf1ccde7b38a60.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 255
```

**Comment by navio-n** [comment]
Also:

Putting MSBuild project build output verbosity to Normal:

1>  [00:00:00.5320249] Done resolving assemblies
1>  Running [E:\User\repos\Uno.Samples\UI\SkiaSharpTest\SkiaSharpTest\SkiaSharpTest.Wasm\obj\Debug\net5.0\workAot]: cmd /c "C:\Users\User\.uno\emsdk\emsdk-3.1.12\emsdk\emsdk_env.bat 2>&1 && C:\Users\Niko\AppData\Local\Temp\dotnet-runtime-wasm-windows-633c7b6-0cee4aaff9c-3338312971-Release\tools\ninja.exe "
1>  [00:00:00.0062749] The system cannot find the path specified.

Only 
.uno-install-done file is found in
C:\Users\User\.uno\emsdk\emsdk-3.1.12\

There is no emsdk folder including emsdk_env.bat

**Comment by navio-n** [comment]
Using the latest versions of Uno and Skiasharp

**Comment by jeromelaban** [comment]
@fatichar this generally means that there's a discrepancy in referenced packages. If you can provide a repro project, it'll help determine which one that is.

@navio-n if you're getting this error, it's likely that emscripten did not get installed properly. It's generally caused by `git` or `python` missing on your system. Try deleting `C:\Users\User.uno\emsdk` and build again.
